# Creating Executables
main :
	gcc main_example_BF.c BF_64.a -no-pie -o ./main_example/main

# ------------------------------------------------- #

# Cleaning Files
clean:
	rm -f ./main_example/main
